digest/urls.py
from django.conf.urls import patterns, include, url
from digest.views import *

urlpatterns = patterns('',
    url(r'^$', manage_diggests),
    url(r'^add_news$', add_news_to_diggest),
    url(r'^(?P<diggest_id>\d+)$', view_old_diggest),
)

digest/models.py
from django.db import models

CHOISE_LANG = (
    ('EN', 'Английский'),
    ('RU', 'Русский'),
    )

class DiggetCategoryNews(models.Model):
    name = models.CharField(max_length=150)
    
    def __unicode__(self):
        return self.name

class DiggestInfo(models.Model):
    first_date = models.DateField()
    last_date = models.DateField()
    href = models.CharField(max_length=150,  blank=True, null=True)
    archive = models.BooleanField(default=False)
    
    def get_diggest_period(self):
        from datetime import timedelta
        
        numdays = (self.last_date - self.first_date).days
        return [self.first_date + timedelta(days=x) for x in range(0, numdays)]
    
    def __unicode__(self):
        return u'Diggest №%s (%s - %s)' % (self.id, self.first_date, self.last_date)        

class DiggestNews(models.Model):
    title = models.CharField(max_length=150)
    href = models.CharField(max_length=500)
    lang = models.CharField(max_length=2, choices=CHOISE_LANG, default='EN')
    category = models.ForeignKey(DiggetCategoryNews)
    desc = models.CharField(max_length=1000, blank=True, null=True)
    add_date = models.DateField(auto_now_add=True)
    diggest = models.ForeignKey(DiggestInfo)
    
    def __unicode__(self):
        return self.title

users/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save 
import os
        
# Create your models here.


class City(models.Model):
    name = models.TextField(max_length=200)

    def __unicode__(self):
        return self.name


class Country(models.Model):
    name = models.TextField(max_length=200)

    def __unicode__(self):
        return self.name

class SocialNet(models.Model):
    network_name = models.CharField(max_length=150)
    link = models.CharField(max_length=200)
    
    def __unicode__(self):
        return self.network_name

class Skills(models.Model):
    name = models.CharField(max_length=50)
    
    def __unicode__(self):
        return self.name
        
class Profile(models.Model):
    user = models.OneToOneField(User, primary_key=True, unique=True)
    avatar = models.ImageField(upload_to="avatars", null=True, blank=True)
    city = models.ForeignKey(City, null=True, blank=True)
    country = models.ForeignKey(Country, null=True, blank=True)
    karma = models.IntegerField(max_length=4, default=0)
    rating = models.IntegerField(max_length=5, default=0)
    about = models.TextField(max_length=1000, null=True, blank=True)
    phone = models.CharField(max_length=15, null=True, blank=True)
    social = models.CharField(max_length=300, null=True, blank=True)
    favorit_post = models.CharField(max_length=1000, null=True, blank=True)
    birthday = models.DateField(null=True, blank=True)
    skills = models.ManyToManyField(Skills, null=True, blank=True)
    
    def __unicode__(self):
        return self.user.username           
    
    def create_avatar(self):
 
        from PIL import Image
        from cStringIO import StringIO
        from django.core.files.uploadedfile import SimpleUploadedFile
         
        AVATAR_SIZE = (200, 200)

        DJANGO_TYPE = self.avatar.file.content_type
 
        if DJANGO_TYPE == 'image/jpeg':
             PIL_TYPE = 'jpeg'
             FILE_EXTENSION = 'jpg'
        elif DJANGO_TYPE == 'image/png':
             PIL_TYPE = 'png'
             FILE_EXTENSION = 'png'
 
        image = Image.open(StringIO(self.avatar.read()))
        usrnm = self.user.username        
        
        image.thumbnail(AVATAR_SIZE, Image.ANTIALIAS)
            
        temp_handle = StringIO()
        image.save(temp_handle, PIL_TYPE)
        temp_handle.seek(0)
        
        suf = SimpleUploadedFile(usrnm, temp_handle.read(), content_type=DJANGO_TYPE)
        
        self.avatar.save('%s.%s'% (usrnm, FILE_EXTENSION), suf, save=False)
                
    def save(self, *args, **kwargs):
        if self.avatar:            
            if 'avatars/' not in self.avatar.name:
                self.create_avatar()
        super(Profile, self).save()

def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

class RakingUsersRate(models.Model):    
    user_voicing = models.ForeignKey(Profile, related_name='ursvoicing')
    raking_user = models.ForeignKey(Profile, related_name='usrrate')     
    voice = models.IntegerField(max_length=2)    

templates/add_post.html
{% extends "base.html" %}
{% load markitup_tags %}

{% block head %}

{% load staticfiles %}
<link rel="stylesheet" href="{% static "css/token-input.css" %}" type="text/css" />
<link rel="stylesheet" href="{% static "css/token-input-facebook.css" %}?{% now "U" %}" type="text/css" />
{% if user.is_authenticated and user.is_superuser%}
<link rel="stylesheet" href="{% static "css/jquery.fileupload.css" %}" type="text/css" >
{% endif %}

<!-- <link rel="stylesheet" href="{% static "css/addpost.css" %}" type="text/css" />-->
{% markitup_media %}
<script type="text/javascript" src="{% static "js/jquery.tokeninput.js" %}"></script>
<script type="text/javascript" src="{% static "js/addpost.js" %}?{% now "U" %}"></script>
{% endblock %}

{% block conten %}
<div class="from_div">
<form action="/add_post" method="post" class='form-horizontal'>{% csrf_token %}
 {% for field in form %}
    {{ field.errors }}
	{{ field.label_tag }} <br>
	{{ field }}<br>
	{% endfor %}
	<input type="submit" name='_save' value='Опубликовать' class='btn btn-success'>   
 </form>
 <br>
   {% if user.is_authenticated and user.is_superuser%}
    {% include "upload_button.html" %} 
 {% endif %}
 </div>
{% endblock %}

templates/base.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<!--[if lt IE 9]><script>document.createElement('nav');</script><![endif]-->
<!--[if lt IE 8]><script>document.createElement('nav');</script><![endif]-->
<!-- <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon" /> -->

<head>
	{% load staticfiles %}
    <meta name='yandex-verification' content='651b848923ab79c7' />
    <meta name="google-site-verification" content="VmDd0WMumM6Fh09NT4q4RBBGE4nSLmD8uDucpmJgfN0" />
	<link rel="stylesheet" href="{% static "css/style.css" %}?{% now "U" %}" type="text/css" media="screen" />
	<!-- <link rel="stylesheet" href="{% static "css/menu.css" %}?{% now "U" %}" type="text/css"/>-->
    <link rel="stylesheet" href="{% static "css/bootstrap.css" %}?{% now "U" %}" type="text/css"/>
    <link rel="stylesheet" href="{% static "css/default.css" %}?{% now "U" %}" type="text/css" />
    <script type="text/javascript" src="{% static "js/highlight.pack.js" %}"></script>
	<script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
    <script type="text/javascript" src="{% static "js/menu.js" %}"></script>
    <script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
	<script type="text/javascript">
    hljs.initHighlightingOnLoad();
    MathJax.Hub.Config({
        "tex2jax": { inlineMath: [ [ '$', '$' ] ] }
    });
    </script>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	{% block head %}
	<title>Блог об анализе данных и ИТ - записки аналитика</title>
	{% endblock %}
</head>

<body>

	<div id="wrapper">
		
		{% block header %}
		<div id="header">
			<div class="logo">
			<h1>Записки аналитика</h1>
			{% if user.is_authenticated %}
			    <h5>
			    <a href='/add_post'>Добавить пост</a>
                </h5>
			{% endif %}
		</div>
		</div>
		<!-- <nav> -->
        <div class='menu'>
			<ul class="nav nav-pills">
				<li><a href='/'>Блог</a></li>
				<li><a href='/howto'>HowTo</a></li>
				<li><a href='/helplink'>Ссылки</a></li>
				<li><a href='/datasets'>Наборы данных</a></li>
                <li><a href='/diggest' title='Все дайджесты со статьями по аналитике в одном месте'>Архив дайджестов</a></li>
                <li><a href='/profile/kuznetsovin'>Об авторе</a></li>
			</ul>
        </div>
		<!-- </nav>-->
		{% endblock %}
		<div id='wrapper'>
		{% block conten %}
		{% endblock %}
		
		{% block sidebar %}
		{% endblock %}
		</div>	
		<div class="clear"></div>
		
		{% block copyright %}	
		<div id="footer">
            <div class='copyrigth'>computerscinese.ru ©</div>
            <div class='feed'>            
            <a class='feed_twitter' href='https://twitter.com/ComputerScinece'></a>             
            <a class='feed_facebook' href='https://www.facebook.com/computerscinese'></a> 
			<a class='feed_vk' href='http://vk.com/public44645555'></a> 
            <a class='feed_rss' href='/rss'></a>
            <a class='feed_subscribe' href="http://subscribe.ru/catalog/comp.web.analisysblog61"></a>
            </div>
			<script>
			  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
			  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
			  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
			  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

			  ga('create', 'UA-43331988-1', 'computerscinece.ru');
			  ga('send', 'pageview');

			</script>
			
			<!-- Yandex.Metrika counter -->
			<script type="text/javascript">
			(function (d, w, c) {
			    (w[c] = w[c] || []).push(function() {
			        try {
			            w.yaCounter23798641 = new Ya.Metrika({id:23798641,
			                    clickmap:true,
			                    trackLinks:true,
			                    accurateTrackBounce:true});
			        } catch(e) { }
			    });

			    var n = d.getElementsByTagName("script")[0],
			        s = d.createElement("script"),
			        f = function () { n.parentNode.insertBefore(s, n); };
			    s.type = "text/javascript";
			    s.async = true;
			    s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

			    if (w.opera == "[object Opera]") {
			        d.addEventListener("DOMContentLoaded", f, false);
			    } else { f(); }
			})(document, window, "yandex_metrika_callbacks");
			</script>
			<noscript><div><img src="//mc.yandex.ru/watch/23798641" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
			<!-- /Yandex.Metrika counter -->
		</div>
		{% endblock %}
	</div>
	
</body>
</html>

templates/diggest-main.html
{% extends "base.html" %}

{% block head %}
{% load staticfiles %}
<link rel="stylesheet" href="{% static "css/bootstrap.css" %}" type="text/css">
<link rel="stylesheet" href="{% static "css/digest.css" %}" type="text/css">
<script src="{% static "js/jquery.js" %}"></script>
<script src="{% static "js/bootstrap.min.js" %}"></script>
<script src="{% static "js/django.form.validation.js" %}"></script>


<title>Дайджест статей по аналитике</title>
{% endblock %}

{% block conten %}
    <div id="content">
        <div class="hentry">
            <div id="main">
                <form class="form-horizontal mainform">
                    <fieldset>
                    <div class="form-group">
                        <div class="input-group">
                            <select class="form-control" id="digest_num">
                               {% for diggest in diggets_archive %}
                              <option value="{{diggest.href}}"> Дайджест № {{diggest.id}} ({{diggest.first_date.day}} - {{diggest.last_date}}) </option>
                              {% endfor %}
                            </select>
                            <span class="input-group-btn">
                                <button class="btn btn-info" type="button" onclick="location.href = $('#digest_num').val()">Посмотреть выпуск</button>
                            </span>
                        </div>
                    </div>
                    <div class="form-group righter">
                        <div class="col-lg-10 col-lg-offset-2">
                            {% if perms.digest.add_diggestnews %}
                            <a data-toggle="modal" href="#modal_win" class="btn btn-success">Добавить новость</a>
                            {% endif %}
                        </div>
                    </div>
                    </fieldset>
                </form>
            </div>
         </div>
    </div>
    
<div class="modal" id="modal_win">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
        <h4 class="modal-title">Добавить статью</h4>
      </div>
      <div class="modal-body">
        <form action="/diggest/add_news" method="POST" class="form-horizontal addform" id='addform'> {% csrf_token %}
                <fieldset>
                {% for field in add_form %}
                <div class="form-group">
                    <label for="{{ field.id }}" class="col-lg-2 control-label">{{ field.label }}</label>
                    <div class="col-lg-10">
                        {{ field }}
                        {{ field.errors }}
                    </div>
                </div>
                {% endfor %}
                <div class="form-group righter">
                    <div class="col-lg-10 col-lg-offset-2">
                       <button type="submit" class="btn btn-success" id="send_form">Добавить материал</button>
                    </div>
                </div>
                </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/diggest-view.html
{% extends "base.html" %}

{% block head %}
<title>Дайджест статей по анализу данных №{{diggest_info.id}} ({{diggest_info.first_date}} - {{diggest_info.last_date}})</title>
{% endblock %}


{% block conten %}
<div id="content">
    <div class="hentry">
        <div id="main">
            <h2>Дайджест статей по анализу данных №{{diggest_info.id}}</h2>
            <h4>{{diggest_info.first_date}} - {{diggest_info.last_date}}</h4>
            {% for article in articles%}
            {% ifchanged %} <h3>{{article.category}}</h3>{% endifchanged %}
            <ul>
            <li><a href="{{ article.href }}">{{ article.title }}</a> ({{ article.lang }})<div class='desc'>{{ article.desc }}</div></li>
            </ul>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

templates/edit_profile.html
{% extends "base.html" %}

{% load staticfiles %}
{% block head %}
<link rel="stylesheet" href="{% static "css/token-input.css" %}" type="text/css" />
<link rel="stylesheet" href="{% static "css/token-input-facebook.css" %}?{% now "U" %}" type="text/css" />
<script type="text/javascript" src="{% static "js/jquery.tokeninput.js" %}"></script>
<script type="text/javascript" src="{% static "js/editprofile.js" %}?{% now "U" %}"></script>
{% endblock %}

{% block conten %}
<div class="from_div">
<h3>Общее</h3>
<form action="" class="form-horizontal editacc" method="POST" enctype="multipart/form-data">{% csrf_token %}
{% for field in form %}
<div class="form-group">
    {{field.errors}}
    <label class="col-lg-2 control-label">{{field.label}}</label>
    <div class="col-lg-10">
    {{field}}
    </div>   
</div>
{% endfor %}
<h3>Контакты</h3>

{% for rec in contacts %}
<div class="form-group">
    <label class="col-lg-2 control-label">{{rec.name}}</label>
    <div class="col-lg-10">
        <div class="input-group">
            <input type="text" class="form-control" id="id_{{rec.name}}" name="{{rec.name}}" value="{{rec.prof}}"/>
            <span class="input-group-btn">
                <button class="btn btn-default" type="button" onclick="del_social(this)">-</button>
            </span>
        </div>
        
    </div>
</div>
{% endfor %}

<div class="form-group" id="appendNet">
    <label class="col-lg-2"> 
    <select id="id_social" name="social" class='form-control' style="padding:0px">
    {% for net in social %}
        <option value="{{ net.id }}">{{ net.network_name }}</option>    
    {% endfor %}
    </select>
    </label>
    <div class="input-group">
        <input type='text' class='form-control' id='profile'/>
        <span class="input-group-btn">
            <button class="btn btn-default" type="button" onclick="add_social()">+</button>
        </span>
    </div>
</div>
<div class="col-lg-10 col-lg-offset-2">
    <input type="submit" class="btn btn-primary" value="Сохранить профиль"/>
</div>
    <input type='hidden' id='skills' value="{{ skills }}">
</form>
</div>
{% endblock %}  

templates/howto.html
{% extends "base.html" %}

{% block conten %}
		<div id="content">
        <div class="hentry">
            <ul>
			{% for link in links %}	
				<li><a href="/posts/{{link.id}}" title="{{ link.title }}">{{ link.title }}</a></li>
			{% endfor %}
            </ul>
        </div>
			
			
						
			<!--<div id="pagination">
                {% if posts.has_previous %}
                    <p class="previous left"><a href="?page={{ posts.previous_page_number }}">&laquo; Previous</a></p>
                {% endif %}
                {% if posts.has_next %}
                    <p class="next right"><a href="?page={{ posts.next_page_number }}"">Next &raquo;</a></p>
                {% endif %}
			</div>-->
			
			<div class="clear"></div>			
		</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}

{% block conten %}
		<div id="content">
			{% for post in posts %}
			<div class="hentry">
				<h4 class="entry-title"><a href="/posts/{{ post.id }}">{{ post.title }}</a></h4>
                {% include "categories_div.html" %}
                {% load plugins %}
				{{ post.text | readmore:post.id | safe}}
				
				<div class="separator"></div>
				<p class="metadata"> <abbr>{{ post.date_post }}</abbr>  &#149; By <a href="/profile/{{ post.author.user.username }}">{{ post.author.user.username }}</a> &#149; <a href="#">{{ post.count_comments }} Comments</a></p>
			</div>
			{% endfor %}
			
						
			<div id="pagination">
                <ul class="pagination pagination-sm">
                {% if posts.has_previous %}
                    <li><a href="?page={{ posts.previous_page_number }}">&laquo;</a></li>
                {% endif %}               
                {% for num in posts.paginator.page_range %}
                      <li><a href="?page={{ num }}">{{ num }}</a></li>
                {% endfor %}
                {% if posts.has_next %}
                    <li><a href="?page={{ posts.next_page_number }}"">&raquo;</a></li>
                {% endif %}
                </ul>
			</div>
			
			<div class="clear"></div>			
		</div>
{% endblock %}

	{% block sidebar %}
		<div id="sidebar">
        
            {{ cats | widget_category | safe}}
                      	
		</div>
    {% endblock %}

templates/login.html
{% extends "base.html" %}
{% block head %}

{% load staticfiles %}
<!-- <link rel="stylesheet" href="{% static "css/formstyleboostrap.css" %}" type="text/css" /> -->

{% endblock %}

{% block conten %}
<div class="from_div div_frm">
<form method="post" action="/login" class="form-horizontal">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-default" value="войти">
</form>
</div>
{% endblock %}

templates/post.html
{% extends "base.html" %}

{% block head %}
{% load markitup_tags %}

{% load staticfiles %}
<link rel="stylesheet" href="{% static "css/comment.css" %}?{% now "U" %}" type="text/css" />
<link rel="stylesheet" href="{% static "markitup/sets/markdown/style.css" %}?{% now "U" %}" media="screen" rel="stylesheet" />
<link rel="stylesheet" href="{% static "markitup/skins/comment/style.css" %}?{% now "U" %}" media="screen" rel="stylesheet" />
<link rel="stylesheet" href="{% static "css/jquery.jgrowl.css" %}?{% now "U" %}" media="screen" rel="stylesheet" />
<link rel="stylesheet" href="{% static "css/message_theme.css" %}?{% now "U" %}" media="screen" rel="stylesheet" />
{% markitup_js %}
<script type="text/javascript" src="{% static "js/rating.js" %}?{% now "U" %}"></script>
<script type="text/javascript" src="{% static "js/comment.js" %}?{% now "U" %}"></script>
<script type="text/javascript" src="{% static "js/jquery.jgrowl.js" %}?{% now "U" %}"></script>
<title>{{ post.title }}</title>
{% endblock %}

{% block conten %}
		<div id="content">
			<div class="hentry">
				<abbr>{{ post.date_post }}</abbr>
				<h3 class="post-title">{{ post.title }}</h3>
                {% include "categories_div.html" %}
                
                {{ post.text | safe}}
                
                <div class="tags" style="padding-top:10px">                
                {% for tag in post.tags.all%}
                <a href="/tags/{{ tag.id }}" target="_blank"><span class="label label-info">{{ tag }}</span>
                {% endfor %}
                </div>
                
				<p class="metadata"> 
					<div id="voicing">
						<a href='#voice' class='plus' {% if user.is_authenticated %} onclick="return voicing(this, 1)" {% else %} onclick="return err_voice()" {% endif %} title='Нравится'></a>
						<div class='rating {{ color }}' id='post_{{ post.id }}'> {{ post.rating }}</div>
						<a href='#voice' class='minus' {% if user.is_authenticated %} onclick="return voicing(this, -1)"  {% else %} onclick="return err_voice()" {% endif %} title='Не нравится'></a>
					</div>&#149;
					<div id='fav'><a href='#favorite' class='{{ fav }}' {% if user.is_authenticated %} onclick="return favorites_post(this,{{ post.id }})"  {% else %} onclick="return err_fav()" {% endif %} title='В избранное'></a></div> &#149;
                    <a href="/profile/{{ post.author.user.username }}">{{ post.author.user.username }}</a> &nbsp {{ g_plus_author | safe }}&#149; 
                    {% include "social_share.html" %}   
					</p>
					
					{% load mptt_tags %}
					<h2 class='comment_title'>Комментарии</h2>
					<div id='print_comment_block'>
					{% recursetree comments %}		
						<div class='comment' style="margin-left: {{ node.get_level }}0px" id='{{ node.id }}'>
							<div class='username'>{{ node.user.user.username }}</div>
							<div class='comment_text'>{{ node.text | linebreaks }}</div>
							<div id="voicing">
								<a href='#' class='plus' {% if user.is_authenticated %}onclick="return voicing(this, 1)"  {% else %} onclick="return err_voice()" {% endif %} title='Нравится'></a>
								<div class='rating {{node.color}}' id='comment_{{ node.id }}'>{{node.rating}}</div>
								<a href='#' class='minus' {% if user.is_authenticated %}onclick="return voicing(this, -1)"  {% else %} onclick="return err_voice()" {% endif %} title='Не нравится'></a> &#149; 								
							</div>
                            {% if user.is_authenticated %}
                            <a onclick="return add_new_comment(this, {{ post.id }})" class='reply'>Ответить</a>
							<div class='reply_form'>
                            {% endif %}
							</div>
						</div>
						
						{% if not node.is_leaf_node %}
							{{ children }}
						{% endif %}
					{% endrecursetree %}
					</div>                   
					 {% if user.is_authenticated %}
                     <div class="comment_div">
                     <a onclick="return add_new_comment(this, {{ post.id }})">Комментировать</a>
                     <form action="" method="post" class='comment_form hidden' id='add_comment'>
                        {% csrf_token %}
                        {{ form_comment.text }}
                        <input type="button" value="Комментировать" class="button" onclick="send_comment(this, {{ post.id }})" />
                     </form>
                     </div>
					{% endif %}
			</div>
			
		</div>
{% endblock %}

templates/preview.html
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static "css/style.css" %}?{% now "U" %}" type="text/css" media="screen" />
	<link rel="stylesheet" href="{% static "css/menu.css" %}?{% now "U" %}" type="text/css"/>
    <link rel="stylesheet" href="{% static "css/default.css" %}" type="text/css" />
    <script type="text/javascript" src="{% static "js/highlight.pack.js" %}"></script>
	<script type="text/javascript" src="{% static "js/jquery.js" %}"></script>
	<script>hljs.initHighlightingOnLoad();</script>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<div>
    <h3 class="post-title">{{ title }}</h3>
	{{ preview|safe }}
</div>

templates/profile.html
{% extends "base.html" %}

{% load staticfiles %}

{% block head %}
<link rel="stylesheet" href="{% static "css/profile.css" %}?{% now "U" %}" type="text/css" />
    <script type="text/javascript" src="{% static "js/userranking.js" %}?{% now "U" %}"></script>
{% endblock %}

{% block conten %}
<div class="from_div" style="width: 700px">
<ul class="nav nav-tabs" style="margin-bottom: 15px;">
  <li class="active"><a href="#profile" data-toggle="tab">Профиль</a></li> 
  <li class=""><a href="#contacts" data-toggle="tab">Контакты</a></li>
  <!-- <li class=""><a href="#favorit" data-toggle="tab">Портфолио</a></li> -->
</ul>
    <div id="myTabContent" class="tab-content">
        <div class="tab-pane fade active in" id="profile">
            <div class='avatar'>
                <img src="/upload/{{ profile.avatar }}">
            </div>
            <div class='info'>
                {% if profile.birthday %}
                <div class='birthday'>
                    <strong>Год рождения:</strong> {{ profile.birthday }}
                </div>
                {% endif %}
                
                {% if profile.country %}
                <div class='country'>
                    <strong>Страна:</strong> {{ profile.country }}
                </div>
                {% endif %}
            
                {% if profile.city %}
                <div class='city'>
                    <strong>Город:</strong> {{ profile.city }}
                </div>
                {% endif %}
            
                {% if profile.about %}
                <div class='about'>
                    <strong>О себе:</strong><br>
                    {{ profile.about }} 
                </div>
                {% endif %}
          </div>
        </div>
     <!-- <div class="tab-pane fade" id="favorit">
      </div>-->
    <div class="tab-pane fade" id="contacts">
        {% for network in social_account %}
            <div class="{{ network.name }}"><div class='linktoprof'><a href="{{ network.link }}">{{ network.account }}</a></div></div>
         {% endfor %}
      </div>
    </div>
</div>
<script type="text/javascript" src="{% static "js/bootstrap.min.js" %}"></script>
<script type="text/javascript" src="{% static "js/bootswatch.js" %}"></script>
{% endblock %}

templates/register.html
{% extends "base.html" %}

{% block conten %}
<div class="from_div div_frm">
	<form action="/registration/" method="post" class="form-horizontal">{% csrf_token %}    
    {{ form.as_p }}
	<input type="submit" class="btn btn-default" value="Регистрация">
	</form>
</div>
{% endblock %}

templates/upload_button.html
    <span class="btn btn-success fileinput-button">
        <i class="glyphicon glyphicon-plus"></i>
        <span>Add files...</span>
        <!-- The file input field used as target for the file upload widget -->
        <input id="fileupload" type="file" name="files[]" multiple>
    </span>
    <br>
    <div id="files" class="files"></div>

{% load staticfiles %}
<script src="{% static "js/jquery.ui.widget.js" %}"></script>
<script src="{% static "js/load-image.min.js" %}"></script>
<script src="{% static "js/jquery.iframe-transport.js" %}"></script>
<script src="{% static "js/jquery.fileupload.js" %}"></script>
<script src="{% static "js/jquery.fileupload-process.js" %}"></script>
<script src="{% static "js/jquery.fileupload-image.js" %}"></script>
<script src="{% static "js/jquery.fileupload-validate.js" %}"></script>
<script src="{% static "js/main_upload.js" %}"></script>